name = "Jexpresso"
uuid = "60551be2-40ab-4403-a4bd-ad35d0cc3d31"
authors = ["Simone Marras <smarras@njit.edu>"]
version = "0.1.0"

[deps]
AMRVW = "233ec0c9-6b8d-4766-b9a2-a16e389fc38a"
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
DiffEqDevTools = "f3b72e0c-5b89-59e1-b016-84e28bfd966d"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
ElasticArrays = "fdbdab4c-e67f-52f5-8c3f-e7b388dad3d4"
Gmsh = "705231aa-382f-11e9-3f0c-b7cb4346fdeb"
Gridap = "56d4f2e9-7ea1-5844-9cf6-b9c51ca7ce8e"
GridapDistributed = "f9701e48-63b3-45aa-9a63-9bc6c271f355"
GridapGmsh = "3025c34a-b394-11e9-2a55-3fee550c04c8"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
Hecke = "3e1990a7-5d81-5526-99ce-9ba3ff248f21"
InternedStrings = "7d512f48-7fb1-5a58-b986-67e6dc259f01"
JLD = "4138dd39-2aa7-5051-a626-17a0bb65d9c8"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
MPIPreferences = "3da0fdf6-3ccc-4f1b-acd9-58baa6c99267"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
PProf = "e4faabce-9ead-11e9-39d9-4379958e3056"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PartitionedArrays = "5a9dfac6-5c52-46f7-8278-5e2210713be9"
PlotlyBase = "a03496cd-edff-5a9b-9e67-9cda94a718b5"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Profile = "9abbd945-dff8-562f-b5e8-e1ebf5ef1b79"
Quadmath = "be4d8f0f-7fa4-5f49-b795-2f01399ab2dd"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SnoopCompile = "aa65fe97-06da-5843-b5b1-d5d13cad87d2"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
TestingUtilities = "40452611-1178-4e48-bdfc-3af4bebad9c9"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"
